export const dependencyLinkCases: readonly { readonly command: string; readonly blocked: boolean }[] = [
  { command: "ln -s ../main/node_modules node_modules", blocked: true },
  { command: "ln -s /home/u/repo/node_modules .", blocked: true },
  { command: "ln -sfn ../main/node_modules/ ./node_modules", blocked: true },
  { command: "ln --symbolic ../main/node_modules", blocked: true },
  { command: "ln -s \"$MAIN/node_modules\" node_modules", blocked: true },
  { command: "cd pkg && ln -s ../../main/node_modules .", blocked: true },
  { command: "npm ci\nln -s ../main/node_modules .", blocked: true },
  { command: "/bin/ln -s ../main/node_modules .", blocked: true },
  { command: "for d in a b; do ln -s ../main/$d/node_modules $d/; done", blocked: true },
  { command: "ln -s -t . ../main/node_modules", blocked: true },
  { command: "ln -s --target-directory=. ../main/node_modules", blocked: true },
  { command: "ln -s ../main/node_modules . 2>/dev/null || true", blocked: true },
  { command: "ln -s ../main/node_modules . > log", blocked: true },
  { command: "ln -s ../main/node_modules . 2> log", blocked: true },
  { command: "ln -s ../main/node_modules . <<EOF\nx\nEOF", blocked: true },
  { command: "npm ci", blocked: false },
  { command: "npm ci --ignore-scripts --no-audit --no-fund", blocked: false },
  { command: "ln -s a b", blocked: false },
  { command: "ln -s node_modules nm", blocked: false },
  { command: "ln -s ../main/node_modules backup", blocked: false },
  { command: "ln -s ../main/node_modules backup > log", blocked: false },
  { command: "ln -sf node_modules/.bin/tsc ~/bin/tsc", blocked: false },
  { command: "ln ../main/node_modules x", blocked: false },
  { command: "ln -s ../pkg node_modules/pkg", blocked: false },
  { command: "ln -s -t node_modules ../pkg", blocked: false },
  { command: "echo 'ln -s ../main/node_modules .'", blocked: false },
  { command: "git commit -m \"docs: never ln -s ../main/node_modules; install instead\"", blocked: false },
  { command: "ls node_modules # ln -s ../main/node_modules .", blocked: false },
  { command: "cat > f <<'EOF'\nln -s ../main/node_modules .\nEOF", blocked: false },
  { command: "cat <<EOF > f\nln -s ../main/node_modules .\nEOF", blocked: false },
  { command: "rm node_modules && npm ci", blocked: false },
  { command: "find . -name node_modules -prune -o -type l -print", blocked: false },
  { command: "cat -s ../main/node_modules", blocked: false },
  { command: "", blocked: false },
];
